# Generated by Django 5.2.7 on 2025-11-05 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedAppointmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('before', 'Before'), ('after', 'After')], max_length=10)),
                ('image_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_images', to='main.bookedappointment')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['booking', 'image_type'], name='main_booked_booking_bdbf02_idx')],
            },
        ),
    ]
