# Generated by Django 5.2.6 on 2025-09-07 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailerprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='image',
        ),
    ]
