# Generated by Django 5.2.6 on 2025-09-08 02:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_detailerprofile_image_remove_vehicles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedappointment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
