# Generated by Django 5.2.7 on 2025-11-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookedappointmentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
    ]
