# Generated by Django 5.2.6 on 2025-09-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_termsandconditions_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='image',
        ),
    ]
