# Generated by Django 5.2.7 on 2025-11-05 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_add_image_to_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='booking_reference',
            field=models.CharField(blank=True, help_text='Booking reference for payments created before booking exists', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='card_brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='last_4_digits',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.bookedappointment'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='currency',
            field=models.CharField(default='eur', max_length=3),
        ),
    ]
