# Generated by Django 5.2.10 on 2026-01-19 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subscriptionplan_subscriptiontier_fleetsubscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDataManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tire_tread_depth', models.DecimalField(blank=True, decimal_places=2, help_text='Tire tread depth in mm', max_digits=5, null=True)),
                ('tire_condition', models.TextField(blank=True, help_text='Notes about tire condition', null=True)),
                ('wiper_status', models.CharField(blank=True, choices=[('good', 'Good'), ('needs_work', 'Needs Work'), ('bad', 'Bad')], max_length=20, null=True)),
                ('oil_level', models.CharField(blank=True, choices=[('good', 'Good'), ('low', 'Low'), ('needs_change', 'Needs Change'), ('needs_refill', 'Needs Refill')], max_length=20, null=True)),
                ('coolant_level', models.CharField(blank=True, choices=[('good', 'Good'), ('low', 'Low'), ('needs_change', 'Needs Change'), ('needs_refill', 'Needs Refill')], max_length=20, null=True)),
                ('brake_fluid_level', models.CharField(blank=True, choices=[('good', 'Good'), ('low', 'Low'), ('needs_change', 'Needs Change'), ('needs_refill', 'Needs Refill')], max_length=20, null=True)),
                ('battery_condition', models.CharField(blank=True, choices=[('good', 'Good'), ('weak', 'Weak'), ('replace', 'Replace')], max_length=20, null=True)),
                ('headlights_status', models.CharField(blank=True, choices=[('working', 'Working'), ('dim', 'Dim'), ('not_working', 'Not Working')], max_length=20, null=True)),
                ('taillights_status', models.CharField(blank=True, choices=[('working', 'Working'), ('dim', 'Dim'), ('not_working', 'Not Working')], max_length=20, null=True)),
                ('indicators_status', models.CharField(blank=True, choices=[('working', 'Working'), ('not_working', 'Not Working')], max_length=20, null=True)),
                ('vehicle_condition_notes', models.TextField(blank=True, help_text='General observations about vehicle condition', null=True)),
                ('damage_report', models.TextField(blank=True, help_text='Notes about any visible damage', null=True)),
                ('inspected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-inspected_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='bookedappointmentimage',
            name='main_booked_booking_bdbf02_idx',
        ),
        migrations.AddField(
            model_name='bookedappointmentimage',
            name='segment',
            field=models.CharField(blank=True, choices=[('interior', 'Interior'), ('exterior', 'Exterior')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fleetmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='bookedappointmentimage',
            index=models.Index(fields=['booking', 'image_type', 'segment'], name='main_booked_booking_a0b5b2_idx'),
        ),
        migrations.AddField(
            model_name='eventdatamanagement',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eventdatamanagement', to='main.bookedappointment'),
        ),
        migrations.AddIndex(
            model_name='eventdatamanagement',
            index=models.Index(fields=['booking'], name='main_eventd_booking_bb1b72_idx'),
        ),
        migrations.AddIndex(
            model_name='eventdatamanagement',
            index=models.Index(fields=['inspected_at'], name='main_eventd_inspect_74ccca_idx'),
        ),
    ]
