# Generated by Django 5.2.10 on 2026-01-19 23:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_eventdatamanagement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('vin_lookup', 'VIN Lookup')], max_length=20),
        ),
        migrations.CreateModel(
            name='VinLookupPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email address (required for all users, Stripe requires email)', max_length=254)),
                ('vin', models.CharField(help_text='Denormalized VIN for quick lookup', max_length=17)),
                ('purchase_reference', models.CharField(help_text='Unique purchase reference (format: VIN-{timestamp}-{uuid})', max_length=255, unique=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Access expires 24 hours from purchase')),
                ('is_active', models.BooleanField(default=True, help_text='True if purchase is not expired')),
                ('payment_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vin_lookup_purchases', to='main.paymenttransaction')),
                ('user', models.ForeignKey(blank=True, help_text='Registered user (nullable for unregistered users)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vin_lookup_purchases', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vin_lookup_purchases', to='main.vehicle')),
            ],
            options={
                'ordering': ['-purchased_at'],
                'indexes': [models.Index(fields=['user', 'vin'], name='main_vinloo_user_id_e8ba1a_idx'), models.Index(fields=['email', 'vin'], name='main_vinloo_email_ff8cba_idx'), models.Index(fields=['vehicle', 'vin'], name='main_vinloo_vehicle_917d3f_idx'), models.Index(fields=['purchase_reference'], name='main_vinloo_purchas_1d3286_idx'), models.Index(fields=['expires_at', 'is_active'], name='main_vinloo_expires_477fdc_idx')],
            },
        ),
    ]
