# Generated by Django 5.2.7 on 2025-11-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_add_unique_phone_to_detailerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedappointment',
            name='subtotal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount before VAT (after discounts)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bookedappointment',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='VAT amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bookedappointment',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=23.0, help_text='VAT rate percentage', max_digits=5),
        ),
    ]
