# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_paymenttransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='spend_limit',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text='Optional cap. 0 or null = no limit.',
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='branch',
            name='spend_limit_period',
            field=models.CharField(
                blank=True,
                choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')],
                max_length=10,
                null=True,
            ),
        ),
    ]
