# Generated by Django 5.2.10 on 2026-01-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_branch_spend_limit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='has_used_trial',
            field=models.BooleanField(default=False, help_text='Whether this fleet has used their trial period'),
        ),
        migrations.AddField(
            model_name='fleet',
            name='trial_used_date',
            field=models.DateTimeField(blank=True, help_text='Date when the fleet used their trial period', null=True),
        ),
        migrations.AddField(
            model_name='fleetsubscription',
            name='grace_period_until',
            field=models.DateTimeField(blank=True, help_text='Grace period end date for payment failures', null=True),
        ),
        migrations.AddField(
            model_name='fleetsubscription',
            name='is_early_adopter',
            field=models.BooleanField(default=False, help_text='Whether this subscription is for an early adopter (first 20)'),
        ),
        migrations.AddField(
            model_name='fleetsubscription',
            name='last_payment_failure_date',
            field=models.DateTimeField(blank=True, help_text='Date of last payment failure', null=True),
        ),
        migrations.AddField(
            model_name='fleetsubscription',
            name='payment_failure_count',
            field=models.IntegerField(default=0, help_text='Number of consecutive payment failures'),
        ),
        migrations.AddField(
            model_name='fleetsubscription',
            name='trial_days',
            field=models.IntegerField(blank=True, help_text='Number of trial days (60 for early adopters, 30 for others)', null=True),
        ),
        migrations.AddField(
            model_name='fleetsubscription',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, help_text='When the trial period ends', null=True),
        ),
        migrations.AddField(
            model_name='fleetsubscription',
            name='trial_start_date',
            field=models.DateTimeField(blank=True, help_text='When the trial period started', null=True),
        ),
        migrations.AlterField(
            model_name='fleetsubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('vin_lookup', 'VIN Lookup'), ('tip', 'Tip'), ('subscription', 'Subscription')], max_length=20),
        ),
    ]
