# Generated by Django 5.2.11 on 2026-02-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_fleet_has_used_trial_fleet_trial_used_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedappointment',
            name='is_express_service',
            field=models.BooleanField(default=False),
        ),
    ]
