# Generated by Django 5.2.11 on 2026-02-13 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_add_partner_business_address'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='commissionearning',
            name='main_commissionearning_unique_partner_booking',
        ),
        migrations.RenameIndex(
            model_name='commissionearning',
            new_name='main_commis_partner_b26fe3_idx',
            old_name='main_commearn_partner_idx',
        ),
        migrations.RenameIndex(
            model_name='commissionearning',
            new_name='main_commis_booking_9cbff6_idx',
            old_name='main_commearn_booking_idx',
        ),
        migrations.RenameIndex(
            model_name='referralattribution',
            new_name='main_referr_partner_741387_idx',
            old_name='main_refattr_partner_idx',
        ),
        migrations.RenameIndex(
            model_name='referralattribution',
            new_name='main_referr_referre_cbfea9_idx',
            old_name='main_refattr_refuser_idx',
        ),
        migrations.AlterUniqueTogether(
            name='commissionearning',
            unique_together={('partner', 'booking')},
        ),
    ]
