# Generated by Django - Referral system fix plan

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_commissionearning_main_commissionearning_unique_partner_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralattribution',
            name='partner_free_wash_used',
            field=models.BooleanField(default=False),
        ),
    ]
