# Generated by Django 5.2.11 on 2026-02-15 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_add_partner_free_wash_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedappointment',
            name='subtotal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookedappointment',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookedappointment',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=23.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='branch',
            name='spend_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='eventdatamanagement',
            name='damage_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventdatamanagement',
            name='tire_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventdatamanagement',
            name='tire_tread_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='eventdatamanagement',
            name='vehicle_condition_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='has_used_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='trial_used_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fleetsubscription',
            name='grace_period_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fleetsubscription',
            name='is_early_adopter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fleetsubscription',
            name='last_payment_failure_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fleetsubscription',
            name='payment_failure_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fleetsubscription',
            name='trial_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fleetsubscription',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fleetsubscription',
            name='trial_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pendingbooking',
            name='booking_data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='pendingbooking',
            name='detailer_booking_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionbilling',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='badge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='yearly_billing_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vinlookuppurchase',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='vinlookuppurchase',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vinlookuppurchase',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vinlookuppurchase',
            name='purchase_reference',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vinlookuppurchase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vin_lookup_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vinlookuppurchase',
            name='vin',
            field=models.CharField(max_length=17),
        ),
    ]
