# Generated by Django 5.2.11 on 2026-02-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_partnerpayoutrequest_iban'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='partnerpayoutrequest',
            new_name='main_partne_partner_ea23ce_idx',
            old_name='main_partne_partner_6a0b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='partnerpayoutrequest',
            new_name='main_partne_status_4025f4_idx',
            old_name='main_partne_status_8b2e8a_idx',
        ),
        migrations.RenameIndex(
            model_name='partnerpayoutrequest',
            new_name='main_partne_request_2a1cf2_idx',
            old_name='main_partne_request_9c3f1e_idx',
        ),
    ]
