# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_main_partne_partner_6a0b0d_idx_main_partne_partner_ea23ce_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedappointment',
            name='review_tip',
        ),
    ]
